/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Management as Code Documents API
 * API del modulo documentale project-scoped di Management as Code.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface DocumentsDocumentIdBody
 */
export interface DocumentsDocumentIdBody {
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdBody
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdBody
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentsDocumentIdBody
     */
    status?: DocumentsDocumentIdBody.StatusEnum;
}

/**
 * @export
 * @namespace DocumentsDocumentIdBody
 */
export namespace DocumentsDocumentIdBody {
    /**
     * @export
     * @enum {string}
     */
    export enum StatusEnum {
        Draft = <any> 'draft',
        InReview = <any> 'in_review',
        Approved = <any> 'approved'
    }
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse200
     */
    timestamp: Date;
}
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {Array<InlineResponse2001Data>}
     * @memberof InlineResponse2001
     */
    data: Array<InlineResponse2001Data>;
    /**
     * 
     * @type {InlineResponse2001Meta}
     * @memberof InlineResponse2001
     */
    meta: InlineResponse2001Meta;
}
/**
 * 
 * @export
 * @interface InlineResponse2001Data
 */
export interface InlineResponse2001Data {
    /**
     * 
     * @type {InlineResponse2001Project}
     * @memberof InlineResponse2001Data
     */
    project: InlineResponse2001Project;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Data
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Data
     */
    name: string;
    /**
     * 
     * @type {any}
     * @memberof InlineResponse2001Data
     */
    parentPackage: any;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Data
     */
    taskCount: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Data
     */
    documentCount: number;
    /**
     * 
     * @type {InlineResponse2001StatusSummary}
     * @memberof InlineResponse2001Data
     */
    statusSummary: InlineResponse2001StatusSummary;
    /**
     * 
     * @type {Array<InlineResponse2001Tasks>}
     * @memberof InlineResponse2001Data
     */
    tasks: Array<InlineResponse2001Tasks>;
}
/**
 * 
 * @export
 * @interface InlineResponse2001Documents
 */
export interface InlineResponse2001Documents {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Documents
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Documents
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Documents
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Documents
     */
    status: InlineResponse2001Documents.StatusEnum;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Documents
     */
    version: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Documents
     */
    updatedAt: string;
    /**
     * 
     * @type {InlineResponse2001Owner}
     * @memberof InlineResponse2001Documents
     */
    owner: InlineResponse2001Owner;
    /**
     * 
     * @type {Array<InlineResponse2001Tags>}
     * @memberof InlineResponse2001Documents
     */
    tags: Array<InlineResponse2001Tags>;
}

/**
 * @export
 * @namespace InlineResponse2001Documents
 */
export namespace InlineResponse2001Documents {
    /**
     * @export
     * @enum {string}
     */
    export enum StatusEnum {
        Draft = <any> 'draft',
        InReview = <any> 'in_review',
        Approved = <any> 'approved',
        Archived = <any> 'archived'
    }
}
/**
 * 
 * @export
 * @interface InlineResponse2001Meta
 */
export interface InlineResponse2001Meta {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Meta
     */
    totalPackages: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Meta
     */
    totalTasks: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Meta
     */
    totalDocuments: number;
}
/**
 * 
 * @export
 * @interface InlineResponse2001Owner
 */
export interface InlineResponse2001Owner {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Owner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Owner
     */
    name: string;
}
/**
 * 
 * @export
 * @interface InlineResponse2001Project
 */
export interface InlineResponse2001Project {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Project
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Project
     */
    name: string;
}
/**
 * 
 * @export
 * @interface InlineResponse2001StatusSummary
 */
export interface InlineResponse2001StatusSummary {
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001StatusSummary
     */
    draft: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001StatusSummary
     */
    inReview: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001StatusSummary
     */
    approved: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001StatusSummary
     */
    archived: number;
}
/**
 * 
 * @export
 * @interface InlineResponse2001Tags
 */
export interface InlineResponse2001Tags {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Tags
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Tags
     */
    name: string;
}
/**
 * 
 * @export
 * @interface InlineResponse2001Tasks
 */
export interface InlineResponse2001Tasks {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Tasks
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2001Tasks
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2001Tasks
     */
    documentCount: number;
    /**
     * 
     * @type {InlineResponse2001StatusSummary}
     * @memberof InlineResponse2001Tasks
     */
    statusSummary: InlineResponse2001StatusSummary;
    /**
     * 
     * @type {Array<InlineResponse2001Documents>}
     * @memberof InlineResponse2001Tasks
     */
    documents: Array<InlineResponse2001Documents>;
}
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {InlineResponse2002Data}
     * @memberof InlineResponse2002
     */
    data: InlineResponse2002Data;
}
/**
 * 
 * @export
 * @interface InlineResponse2002Data
 */
export interface InlineResponse2002Data {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Data
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Data
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Data
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Data
     */
    status: InlineResponse2002Data.StatusEnum;
    /**
     * 
     * @type {InlineResponse2001Project}
     * @memberof InlineResponse2002Data
     */
    project: InlineResponse2001Project;
    /**
     * 
     * @type {InlineResponse2002DataPackage}
     * @memberof InlineResponse2002Data
     */
    _package: InlineResponse2002DataPackage;
    /**
     * 
     * @type {ModelNull | any}
     * @memberof InlineResponse2002Data
     */
    parentPackage: ModelNull | any;
    /**
     * 
     * @type {InlineResponse2002DataTask}
     * @memberof InlineResponse2002Data
     */
    task: InlineResponse2002DataTask;
    /**
     * 
     * @type {InlineResponse2001Owner}
     * @memberof InlineResponse2002Data
     */
    owner: InlineResponse2001Owner;
    /**
     * 
     * @type {InlineResponse2002DataFileInfo}
     * @memberof InlineResponse2002Data
     */
    fileInfo: InlineResponse2002DataFileInfo;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002Data
     */
    version: number;
    /**
     * 
     * @type {Date}
     * @memberof InlineResponse2002Data
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Data
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002Data
     */
    archivedAt?: string;
    /**
     * 
     * @type {Array<InlineResponse2001Tags>}
     * @memberof InlineResponse2002Data
     */
    tags: Array<InlineResponse2001Tags>;
}

/**
 * @export
 * @namespace InlineResponse2002Data
 */
export namespace InlineResponse2002Data {
    /**
     * @export
     * @enum {string}
     */
    export enum StatusEnum {
        Draft = <any> 'draft',
        InReview = <any> 'in_review',
        Approved = <any> 'approved',
        Archived = <any> 'archived'
    }
}
/**
 * 
 * @export
 * @interface InlineResponse2002DataFileInfo
 */
export interface InlineResponse2002DataFileInfo {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DataFileInfo
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DataFileInfo
     */
    mimeType: string;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2002DataFileInfo
     */
    sizeBytes: number;
}
/**
 * 
 * @export
 * @interface InlineResponse2002DataPackage
 */
export interface InlineResponse2002DataPackage {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DataPackage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DataPackage
     */
    name: string;
}
/**
 * 
 * @export
 * @interface InlineResponse2002DataTask
 */
export interface InlineResponse2002DataTask {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DataTask
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2002DataTask
     */
    name: string;
}
/**
 * 
 * @export
 * @interface InlineResponse400
 */
export interface InlineResponse400 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse400
     */
    message: string;
}
/**
 * HealthApi - fetch parameter creator
 * @export
 */
export const HealthApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Verifica che il backend sia avviato.
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/health`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Verifica che il backend sia avviato.
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InlineResponse200> {
            const localVarFetchArgs = HealthApiFetchParamCreator(configuration).healthControllerGetHealth(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Verifica che il backend sia avviato.
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options?: any) {
            return HealthApiFp(configuration).healthControllerGetHealth(options)(fetch, basePath);
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Verifica che il backend sia avviato.
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthControllerGetHealth(options?: any) {
        return HealthApiFp(this.configuration).healthControllerGetHealth(options)(this.fetch, this.basePath);
    }

}
/**
 * ProjectDocumentsApi - fetch parameter creator
 * @export
 */
export const ProjectDocumentsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Archivia logicamente il documento impostando status archived e archivedAt.
         * @summary Archive project document
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerArchiveProjectDocument.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerArchiveProjectDocument.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Scarica il file associato al documento.
         * @summary Download project document file
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerDownloadProjectDocumentFile.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerDownloadProjectDocumentFile.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}/file`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restituisce il dettaglio di un documento appartenente al progetto indicato.
         * @summary Get project document by id
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerGetProjectDocumentById.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerGetProjectDocumentById.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restituisce la home documentale del progetto, con documenti raggruppati per package e task.
         * @summary List project documents
         * @param {any} projectId ID del progetto
         * @param {any} [search] 
         * @param {string} [status] 
         * @param {any} [tag] 
         * @param {any} [ownerId] 
         * @param {any} [taskId] 
         * @param {any} [packageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options: any = {}): FetchArgs {
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerListProjectDocuments.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (tag !== undefined) {
                localVarQueryParameter['tag'] = tag;
            }

            if (ownerId !== undefined) {
                localVarQueryParameter['ownerId'] = ownerId;
            }

            if (taskId !== undefined) {
                localVarQueryParameter['taskId'] = taskId;
            }

            if (packageId !== undefined) {
                localVarQueryParameter['packageId'] = packageId;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aggiorna i campi modificabili di un documento non archiviato.
         * @summary Update project document
         * @param {DocumentsDocumentIdBody} body 
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerUpdateProjectDocument(body: DocumentsDocumentIdBody, documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling projectDocumentsControllerUpdateProjectDocument.');
            }
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerUpdateProjectDocument.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerUpdateProjectDocument.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"DocumentsDocumentIdBody" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectDocumentsApi - functional programming interface
 * @export
 */
export const ProjectDocumentsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Archivia logicamente il documento impostando status archived e archivedAt.
         * @summary Archive project document
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InlineResponse2002> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerArchiveProjectDocument(documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Scarica il file associato al documento.
         * @summary Download project document file
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Blob> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Restituisce il dettaglio di un documento appartenente al progetto indicato.
         * @summary Get project document by id
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InlineResponse2002> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerGetProjectDocumentById(documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Restituisce la home documentale del progetto, con documenti raggruppati per package e task.
         * @summary List project documents
         * @param {any} projectId ID del progetto
         * @param {any} [search] 
         * @param {string} [status] 
         * @param {any} [tag] 
         * @param {any} [ownerId] 
         * @param {any} [taskId] 
         * @param {any} [packageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InlineResponse2001> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Aggiorna i campi modificabili di un documento non archiviato.
         * @summary Update project document
         * @param {DocumentsDocumentIdBody} body 
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerUpdateProjectDocument(body: DocumentsDocumentIdBody, documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<InlineResponse2002> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ProjectDocumentsApi - factory interface
 * @export
 */
export const ProjectDocumentsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Archivia logicamente il documento impostando status archived e archivedAt.
         * @summary Archive project document
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerArchiveProjectDocument(documentId, projectId, options)(fetch, basePath);
        },
        /**
         * Scarica il file associato al documento.
         * @summary Download project document file
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, options)(fetch, basePath);
        },
        /**
         * Restituisce il dettaglio di un documento appartenente al progetto indicato.
         * @summary Get project document by id
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerGetProjectDocumentById(documentId, projectId, options)(fetch, basePath);
        },
        /**
         * Restituisce la home documentale del progetto, con documenti raggruppati per package e task.
         * @summary List project documents
         * @param {any} projectId ID del progetto
         * @param {any} [search] 
         * @param {string} [status] 
         * @param {any} [tag] 
         * @param {any} [ownerId] 
         * @param {any} [taskId] 
         * @param {any} [packageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, options)(fetch, basePath);
        },
        /**
         * Aggiorna i campi modificabili di un documento non archiviato.
         * @summary Update project document
         * @param {DocumentsDocumentIdBody} body 
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerUpdateProjectDocument(body: DocumentsDocumentIdBody, documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, options)(fetch, basePath);
        },
    };
};

/**
 * ProjectDocumentsApi - object-oriented interface
 * @export
 * @class ProjectDocumentsApi
 * @extends {BaseAPI}
 */
export class ProjectDocumentsApi extends BaseAPI {
    /**
     * Archivia logicamente il documento impostando status archived e archivedAt.
     * @summary Archive project document
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerArchiveProjectDocument(documentId, projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Scarica il file associato al documento.
     * @summary Download project document file
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Restituisce il dettaglio di un documento appartenente al progetto indicato.
     * @summary Get project document by id
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerGetProjectDocumentById(documentId, projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Restituisce la home documentale del progetto, con documenti raggruppati per package e task.
     * @summary List project documents
     * @param {any} projectId ID del progetto
     * @param {any} [search] 
     * @param {string} [status] 
     * @param {any} [tag] 
     * @param {any} [ownerId] 
     * @param {any} [taskId] 
     * @param {any} [packageId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, options)(this.fetch, this.basePath);
    }

    /**
     * Aggiorna i campi modificabili di un documento non archiviato.
     * @summary Update project document
     * @param {DocumentsDocumentIdBody} body 
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerUpdateProjectDocument(body: DocumentsDocumentIdBody, documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, options)(this.fetch, this.basePath);
    }

}
