/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * Management as Code Documents API
 * API del modulo documentale project-scoped di Management as Code.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "http://localhost:3000".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * 
     * @type {string}
     * @memberof ApiError
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof ApiError
     */
    message: string;
}
/**
 * 
 * @export
 * @interface DocumentDetail
 */
export interface DocumentDetail {
    /**
     * 
     * @type {string}
     * @memberof DocumentDetail
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentDetail
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentDetail
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentDetail
     */
    status: DocumentDetail.StatusEnum;
    /**
     * 
     * @type {ProjectRef}
     * @memberof DocumentDetail
     */
    project: ProjectRef;
    /**
     * 
     * @type {PackageRef}
     * @memberof DocumentDetail
     */
    _package: PackageRef;
    /**
     * 
     * @type {ParentPackageRef}
     * @memberof DocumentDetail
     */
    parentPackage: ParentPackageRef;
    /**
     * 
     * @type {TaskRef}
     * @memberof DocumentDetail
     */
    task: TaskRef;
    /**
     * 
     * @type {DocumentOwner}
     * @memberof DocumentDetail
     */
    owner: DocumentOwner;
    /**
     * 
     * @type {FileInfo}
     * @memberof DocumentDetail
     */
    fileInfo: FileInfo;
    /**
     * 
     * @type {number}
     * @memberof DocumentDetail
     */
    version: number;
    /**
     * 
     * @type {Date}
     * @memberof DocumentDetail
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentDetail
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentDetail
     */
    archivedAt: Date;
    /**
     * 
     * @type {Array<DocumentTag>}
     * @memberof DocumentDetail
     */
    tags: Array<DocumentTag>;
}

/**
 * @export
 * @namespace DocumentDetail
 */
export namespace DocumentDetail {
    /**
     * @export
     * @enum {string}
     */
    export enum StatusEnum {
        Draft = <any> 'draft',
        InReview = <any> 'in_review',
        Approved = <any> 'approved',
        Archived = <any> 'archived'
    }
}
/**
 * 
 * @export
 * @interface DocumentDetailResponse
 */
export interface DocumentDetailResponse {
    /**
     * 
     * @type {DocumentDetail}
     * @memberof DocumentDetailResponse
     */
    data: DocumentDetail;
}
/**
 * 
 * @export
 * @interface DocumentHomeMeta
 */
export interface DocumentHomeMeta {
    /**
     * 
     * @type {number}
     * @memberof DocumentHomeMeta
     */
    totalPackages: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentHomeMeta
     */
    totalTasks: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentHomeMeta
     */
    totalDocuments: number;
}
/**
 * 
 * @export
 * @interface DocumentHomeResponse
 */
export interface DocumentHomeResponse {
    /**
     * 
     * @type {Array<DocumentPackageGroup>}
     * @memberof DocumentHomeResponse
     */
    data: Array<DocumentPackageGroup>;
    /**
     * 
     * @type {DocumentHomeMeta}
     * @memberof DocumentHomeResponse
     */
    meta: DocumentHomeMeta;
}
/**
 * 
 * @export
 * @interface DocumentListItem
 */
export interface DocumentListItem {
    /**
     * 
     * @type {string}
     * @memberof DocumentListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentListItem
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentListItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentListItem
     */
    status: DocumentListItem.StatusEnum;
    /**
     * 
     * @type {number}
     * @memberof DocumentListItem
     */
    version: number;
    /**
     * 
     * @type {Date}
     * @memberof DocumentListItem
     */
    updatedAt: Date;
    /**
     * 
     * @type {DocumentOwner}
     * @memberof DocumentListItem
     */
    owner: DocumentOwner;
    /**
     * 
     * @type {Array<DocumentTag>}
     * @memberof DocumentListItem
     */
    tags: Array<DocumentTag>;
}

/**
 * @export
 * @namespace DocumentListItem
 */
export namespace DocumentListItem {
    /**
     * @export
     * @enum {string}
     */
    export enum StatusEnum {
        Draft = <any> 'draft',
        InReview = <any> 'in_review',
        Approved = <any> 'approved',
        Archived = <any> 'archived'
    }
}
/**
 * 
 * @export
 * @interface DocumentOwner
 */
export interface DocumentOwner {
    /**
     * 
     * @type {string}
     * @memberof DocumentOwner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentOwner
     */
    name: string;
}
/**
 * 
 * @export
 * @interface DocumentPackageGroup
 */
export interface DocumentPackageGroup {
    /**
     * 
     * @type {ProjectRef}
     * @memberof DocumentPackageGroup
     */
    project: ProjectRef;
    /**
     * 
     * @type {string}
     * @memberof DocumentPackageGroup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentPackageGroup
     */
    name: string;
    /**
     * 
     * @type {ParentPackageRef}
     * @memberof DocumentPackageGroup
     */
    parentPackage: ParentPackageRef;
    /**
     * 
     * @type {number}
     * @memberof DocumentPackageGroup
     */
    taskCount: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentPackageGroup
     */
    documentCount: number;
    /**
     * 
     * @type {DocumentStatusSummary}
     * @memberof DocumentPackageGroup
     */
    statusSummary: DocumentStatusSummary;
    /**
     * 
     * @type {Array<DocumentTaskGroup>}
     * @memberof DocumentPackageGroup
     */
    tasks: Array<DocumentTaskGroup>;
}
/**
 * 
 * @export
 * @interface DocumentStatusSummary
 */
export interface DocumentStatusSummary {
    /**
     * 
     * @type {number}
     * @memberof DocumentStatusSummary
     */
    draft: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentStatusSummary
     */
    inReview: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentStatusSummary
     */
    approved: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentStatusSummary
     */
    archived: number;
}
/**
 * 
 * @export
 * @interface DocumentTag
 */
export interface DocumentTag {
    /**
     * 
     * @type {string}
     * @memberof DocumentTag
     */
    name: string;
}
/**
 * 
 * @export
 * @interface DocumentTaskGroup
 */
export interface DocumentTaskGroup {
    /**
     * 
     * @type {string}
     * @memberof DocumentTaskGroup
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentTaskGroup
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentTaskGroup
     */
    documentCount: number;
    /**
     * 
     * @type {DocumentStatusSummary}
     * @memberof DocumentTaskGroup
     */
    statusSummary: DocumentStatusSummary;
    /**
     * 
     * @type {Array<DocumentListItem>}
     * @memberof DocumentTaskGroup
     */
    documents: Array<DocumentListItem>;
}
/**
 * 
 * @export
 * @interface DocumentTreeMeta
 */
export interface DocumentTreeMeta {
    /**
     * 
     * @type {number}
     * @memberof DocumentTreeMeta
     */
    totalPackages: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentTreeMeta
     */
    totalTasks: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentTreeMeta
     */
    totalDocuments: number;
}
/**
 * 
 * @export
 * @interface DocumentTreePackage
 */
export interface DocumentTreePackage {
    /**
     * 
     * @type {string}
     * @memberof DocumentTreePackage
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentTreePackage
     */
    name: string;
    /**
     * 
     * @type {ParentPackageRef}
     * @memberof DocumentTreePackage
     */
    parentPackage: ParentPackageRef;
    /**
     * 
     * @type {number}
     * @memberof DocumentTreePackage
     */
    taskCount: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentTreePackage
     */
    documentCount: number;
    /**
     * 
     * @type {DocumentStatusSummary}
     * @memberof DocumentTreePackage
     */
    statusSummary: DocumentStatusSummary;
    /**
     * 
     * @type {Array<DocumentTreeTask>}
     * @memberof DocumentTreePackage
     */
    tasks: Array<DocumentTreeTask>;
}
/**
 * 
 * @export
 * @interface DocumentTreeResponse
 */
export interface DocumentTreeResponse {
    /**
     * 
     * @type {Array<DocumentTreePackage>}
     * @memberof DocumentTreeResponse
     */
    data: Array<DocumentTreePackage>;
    /**
     * 
     * @type {DocumentTreeMeta}
     * @memberof DocumentTreeResponse
     */
    meta: DocumentTreeMeta;
}
/**
 * 
 * @export
 * @interface DocumentTreeTask
 */
export interface DocumentTreeTask {
    /**
     * 
     * @type {string}
     * @memberof DocumentTreeTask
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentTreeTask
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentTreeTask
     */
    documentCount: number;
    /**
     * 
     * @type {DocumentStatusSummary}
     * @memberof DocumentTreeTask
     */
    statusSummary: DocumentStatusSummary;
}
/**
 * 
 * @export
 * @interface FileInfo
 */
export interface FileInfo {
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    fileName: string;
    /**
     * 
     * @type {string}
     * @memberof FileInfo
     */
    mimeType: string;
    /**
     * 
     * @type {number}
     * @memberof FileInfo
     */
    sizeBytes: number;
}
/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    status: string;
    /**
     * 
     * @type {Date}
     * @memberof HealthResponse
     */
    timestamp: Date;
}
/**
 * 
 * @export
 * @interface PackageRef
 */
export interface PackageRef {
    /**
     * 
     * @type {string}
     * @memberof PackageRef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PackageRef
     */
    name: string;
}
/**
 * 
 * @export
 * @interface ParentPackageRef
 */
export interface ParentPackageRef {
    /**
     * 
     * @type {string}
     * @memberof ParentPackageRef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ParentPackageRef
     */
    name: string;
}
/**
 * 
 * @export
 * @interface ProjectRef
 */
export interface ProjectRef {
    /**
     * 
     * @type {string}
     * @memberof ProjectRef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectRef
     */
    name: string;
}
/**
 * 
 * @export
 * @interface TaskRef
 */
export interface TaskRef {
    /**
     * 
     * @type {string}
     * @memberof TaskRef
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TaskRef
     */
    name: string;
}
/**
 * 
 * @export
 * @interface UpdateDocumentRequest
 */
export interface UpdateDocumentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateDocumentRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDocumentRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateDocumentRequest
     */
    status?: UpdateDocumentRequest.StatusEnum;
}

/**
 * @export
 * @namespace UpdateDocumentRequest
 */
export namespace UpdateDocumentRequest {
    /**
     * @export
     * @enum {string}
     */
    export enum StatusEnum {
        Draft = <any> 'draft',
        InReview = <any> 'in_review',
        Approved = <any> 'approved'
    }
}
/**
 * HealthApi - fetch parameter creator
 * @export
 */
export const HealthApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Verifica che il backend sia avviato.
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options: any = {}): FetchArgs {
            const localVarPath = `/api/v1/health`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Verifica che il backend sia avviato.
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<HealthResponse> {
            const localVarFetchArgs = HealthApiFetchParamCreator(configuration).healthControllerGetHealth(options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Verifica che il backend sia avviato.
         * @summary Health check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options?: any) {
            return HealthApiFp(configuration).healthControllerGetHealth(options)(fetch, basePath);
        },
    };
};

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI {
    /**
     * Verifica che il backend sia avviato.
     * @summary Health check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthControllerGetHealth(options?: any) {
        return HealthApiFp(this.configuration).healthControllerGetHealth(options)(this.fetch, this.basePath);
    }

}
/**
 * ProjectDocumentsApi - fetch parameter creator
 * @export
 */
export const ProjectDocumentsApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Archivia logicamente il documento impostando status archived e archivedAt.
         * @summary Archive project document
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerArchiveProjectDocument.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerArchiveProjectDocument.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Scarica il file associato al documento.
         * @summary Download project document file
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerDownloadProjectDocumentFile.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerDownloadProjectDocumentFile.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}/file`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restituisce il dettaglio di un documento appartenente al progetto indicato.
         * @summary Get project document by id
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerGetProjectDocumentById.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerGetProjectDocumentById.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restituisce una struttura leggera package -> task con conteggi, senza caricare i dettagli dei documenti.
         * @summary Get project document tree
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentTree(projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerGetProjectDocumentTree.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/document-tree`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Restituisce la home documentale del progetto, con documenti raggruppati per package e task e filtrabili tramite query parameters.
         * @summary List project documents
         * @param {any} projectId ID del progetto
         * @param {any} [search] 
         * @param {string} [status] 
         * @param {any} [tag] 
         * @param {any} [ownerId] 
         * @param {any} [taskId] 
         * @param {any} [packageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options: any = {}): FetchArgs {
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerListProjectDocuments.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (tag !== undefined) {
                localVarQueryParameter['tag'] = tag;
            }

            if (ownerId !== undefined) {
                localVarQueryParameter['ownerId'] = ownerId;
            }

            if (taskId !== undefined) {
                localVarQueryParameter['taskId'] = taskId;
            }

            if (packageId !== undefined) {
                localVarQueryParameter['packageId'] = packageId;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aggiorna i campi modificabili di un documento non archiviato.
         * @summary Update project document
         * @param {UpdateDocumentRequest} body 
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerUpdateProjectDocument(body: UpdateDocumentRequest, documentId: string, projectId: any, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling projectDocumentsControllerUpdateProjectDocument.');
            }
            // verify required parameter 'documentId' is not null or undefined
            if (documentId === null || documentId === undefined) {
                throw new RequiredError('documentId','Required parameter documentId was null or undefined when calling projectDocumentsControllerUpdateProjectDocument.');
            }
            // verify required parameter 'projectId' is not null or undefined
            if (projectId === null || projectId === undefined) {
                throw new RequiredError('projectId','Required parameter projectId was null or undefined when calling projectDocumentsControllerUpdateProjectDocument.');
            }
            const localVarPath = `/api/v1/projects/{projectId}/documents/{documentId}`
                .replace(`{${"documentId"}}`, encodeURIComponent(String(documentId)))
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UpdateDocumentRequest" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectDocumentsApi - functional programming interface
 * @export
 */
export const ProjectDocumentsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Archivia logicamente il documento impostando status archived e archivedAt.
         * @summary Archive project document
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DocumentDetailResponse> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerArchiveProjectDocument(documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Scarica il file associato al documento.
         * @summary Download project document file
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Blob> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Restituisce il dettaglio di un documento appartenente al progetto indicato.
         * @summary Get project document by id
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DocumentDetailResponse> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerGetProjectDocumentById(documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Restituisce una struttura leggera package -> task con conteggi, senza caricare i dettagli dei documenti.
         * @summary Get project document tree
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentTree(projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DocumentTreeResponse> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerGetProjectDocumentTree(projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Restituisce la home documentale del progetto, con documenti raggruppati per package e task e filtrabili tramite query parameters.
         * @summary List project documents
         * @param {any} projectId ID del progetto
         * @param {any} [search] 
         * @param {string} [status] 
         * @param {any} [tag] 
         * @param {any} [ownerId] 
         * @param {any} [taskId] 
         * @param {any} [packageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DocumentHomeResponse> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Aggiorna i campi modificabili di un documento non archiviato.
         * @summary Update project document
         * @param {UpdateDocumentRequest} body 
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerUpdateProjectDocument(body: UpdateDocumentRequest, documentId: string, projectId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<DocumentDetailResponse> {
            const localVarFetchArgs = ProjectDocumentsApiFetchParamCreator(configuration).projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * ProjectDocumentsApi - factory interface
 * @export
 */
export const ProjectDocumentsApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Archivia logicamente il documento impostando status archived e archivedAt.
         * @summary Archive project document
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerArchiveProjectDocument(documentId, projectId, options)(fetch, basePath);
        },
        /**
         * Scarica il file associato al documento.
         * @summary Download project document file
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, options)(fetch, basePath);
        },
        /**
         * Restituisce il dettaglio di un documento appartenente al progetto indicato.
         * @summary Get project document by id
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerGetProjectDocumentById(documentId, projectId, options)(fetch, basePath);
        },
        /**
         * Restituisce una struttura leggera package -> task con conteggi, senza caricare i dettagli dei documenti.
         * @summary Get project document tree
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerGetProjectDocumentTree(projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerGetProjectDocumentTree(projectId, options)(fetch, basePath);
        },
        /**
         * Restituisce la home documentale del progetto, con documenti raggruppati per package e task e filtrabili tramite query parameters.
         * @summary List project documents
         * @param {any} projectId ID del progetto
         * @param {any} [search] 
         * @param {string} [status] 
         * @param {any} [tag] 
         * @param {any} [ownerId] 
         * @param {any} [taskId] 
         * @param {any} [packageId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, options)(fetch, basePath);
        },
        /**
         * Aggiorna i campi modificabili di un documento non archiviato.
         * @summary Update project document
         * @param {UpdateDocumentRequest} body 
         * @param {string} documentId ID del documento nel formato DOC-001
         * @param {any} projectId ID del progetto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        projectDocumentsControllerUpdateProjectDocument(body: UpdateDocumentRequest, documentId: string, projectId: any, options?: any) {
            return ProjectDocumentsApiFp(configuration).projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, options)(fetch, basePath);
        },
    };
};

/**
 * ProjectDocumentsApi - object-oriented interface
 * @export
 * @class ProjectDocumentsApi
 * @extends {BaseAPI}
 */
export class ProjectDocumentsApi extends BaseAPI {
    /**
     * Archivia logicamente il documento impostando status archived e archivedAt.
     * @summary Archive project document
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerArchiveProjectDocument(documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerArchiveProjectDocument(documentId, projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Scarica il file associato al documento.
     * @summary Download project document file
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerDownloadProjectDocumentFile(documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Restituisce il dettaglio di un documento appartenente al progetto indicato.
     * @summary Get project document by id
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerGetProjectDocumentById(documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerGetProjectDocumentById(documentId, projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Restituisce una struttura leggera package -> task con conteggi, senza caricare i dettagli dei documenti.
     * @summary Get project document tree
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerGetProjectDocumentTree(projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerGetProjectDocumentTree(projectId, options)(this.fetch, this.basePath);
    }

    /**
     * Restituisce la home documentale del progetto, con documenti raggruppati per package e task e filtrabili tramite query parameters.
     * @summary List project documents
     * @param {any} projectId ID del progetto
     * @param {any} [search] 
     * @param {string} [status] 
     * @param {any} [tag] 
     * @param {any} [ownerId] 
     * @param {any} [taskId] 
     * @param {any} [packageId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerListProjectDocuments(projectId: any, search?: any, status?: string, tag?: any, ownerId?: any, taskId?: any, packageId?: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, options)(this.fetch, this.basePath);
    }

    /**
     * Aggiorna i campi modificabili di un documento non archiviato.
     * @summary Update project document
     * @param {UpdateDocumentRequest} body 
     * @param {string} documentId ID del documento nel formato DOC-001
     * @param {any} projectId ID del progetto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectDocumentsApi
     */
    public projectDocumentsControllerUpdateProjectDocument(body: UpdateDocumentRequest, documentId: string, projectId: any, options?: any) {
        return ProjectDocumentsApiFp(this.configuration).projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, options)(this.fetch, this.basePath);
    }

}
