/**
 * Management as Code Documents API
 * API del modulo documentale project-scoped di Management as Code.
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("HealthApi", () => {
  let instance: api.HealthApi
  beforeEach(function() {
    instance = new api.HealthApi(config)
  });

  test("healthControllerGetHealth", () => {
    return expect(instance.healthControllerGetHealth({})).resolves.toBe(null)
  })
})

describe("ProjectDocumentsApi", () => {
  let instance: api.ProjectDocumentsApi
  beforeEach(function() {
    instance = new api.ProjectDocumentsApi(config)
  });

  test("projectDocumentsControllerArchiveProjectDocument", () => {
    const documentId: string = "documentId_example"
    const projectId: any = undefined
    return expect(instance.projectDocumentsControllerArchiveProjectDocument(documentId, projectId, {})).resolves.toBe(null)
  })
  test("projectDocumentsControllerDownloadProjectDocumentFile", () => {
    const documentId: string = "documentId_example"
    const projectId: any = undefined
    return expect(instance.projectDocumentsControllerDownloadProjectDocumentFile(documentId, projectId, {})).resolves.toBe(null)
  })
  test("projectDocumentsControllerGetProjectDocumentById", () => {
    const documentId: string = "documentId_example"
    const projectId: any = undefined
    return expect(instance.projectDocumentsControllerGetProjectDocumentById(documentId, projectId, {})).resolves.toBe(null)
  })
  test("projectDocumentsControllerListProjectDocuments", () => {
    const projectId: any = undefined
    const search: any = undefined
    const status: string = "status_example"
    const tag: any = undefined
    const ownerId: any = undefined
    const taskId: any = undefined
    const packageId: any = undefined
    return expect(instance.projectDocumentsControllerListProjectDocuments(projectId, search, status, tag, ownerId, taskId, packageId, {})).resolves.toBe(null)
  })
  test("projectDocumentsControllerUpdateProjectDocument", () => {
    const body: api.DocumentsDocumentIdBody = undefined
    const documentId: string = "documentId_example"
    const projectId: any = undefined
    return expect(instance.projectDocumentsControllerUpdateProjectDocument(body, documentId, projectId, {})).resolves.toBe(null)
  })
})

